# Generated by Django 4.0.3 on 2023-05-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_views',
            field=models.ManyToManyField(blank=True, to='rbac.permissionview', verbose_name='权限'),
        ),
    ]
